services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - main



  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: unless-stopped
    command: "azurite --blobHost 0.0.0.0 --location /data --debug /data/debug.log --skipApiVersionCheck --loose"
    ports:
      - "10000:10000"
    volumes:
      - azurite_data:/data
    networks:
      - main


  nginx:
    image: nginx:alpine
    restart: unless-stopped
    profiles: ["proxy"]
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - main

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  sqlserver_data:
  azurite_data:
  redis_data:

networks: 
  main:
    driver: bridge
