services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - main

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: unless-stopped
    command: "azurite --blobHost 0.0.0.0 --location /data --debug /data/debug.log --skipApiVersionCheck --loose"
    ports:
      - "10000:10000"
    volumes:
      - azurite_data:/data
    networks:
      - main

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    profiles: ["proxy"]
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - main

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - main
  
  servicebus-emulator:
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "5300:5300"
    environment:
      ACCEPT_EULA: "Y"
      SQL_SERVER: sqlserver
      MSSQL_SA_PASSWORD: ${SQL_SA_PASSWORD}
      CONFIG_FILE: /ServiceBus_Emulator/ConfigFiles/Config.json
    volumes:
      - ./servicebus-config.json:/ServiceBus_Emulator/ConfigFiles/Config.json
      - servicebus_data:/ServiceBus_Emulator
    depends_on:
      - sqlserver
    networks:
      - main

  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
      - "10250-10255:10250-10255"
    environment:
      - AZURE_COSMOS_EMULATOR_PARTITION_COUNT=3
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
      - AZURE_COSMOS_EMULATOR_IP_ADDRESS_OVERRIDE=127.0.0.1
    volumes:
      - cosmosdb-data:/tmp/cosmos/appdata

volumes:
  sqlserver_data:
  azurite_data:
  redis_data:
  servicebus_data:
  cosmosdb-data:

networks: 
  main:
    driver: bridge
