<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
		<PackageReference Include="Azure.Storage.Blobs" Version="12.27.0" />
		<PackageReference Include="Hangfire.AspNetCore" Version="1.8.23" />
		<PackageReference Include="Hangfire.SqlServer" Version="1.8.23" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.22" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="9.0.4" />
		<PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="8.0.0" />
		<PackageReference Include="Microsoft.KernelMemory.AI.AzureOpenAI" Version="0.98.250508.3" />
		<PackageReference Include="Microsoft.KernelMemory.Core" Version="0.98.250508.3" />
		<PackageReference Include="Microsoft.KernelMemory.MemoryDb.AzureAISearch" Version="0.98.250508.3" />
		<PackageReference Include="StackExchange.Redis" Version="2.11.3" />
		<PackageReference Include="Stripe.net" Version="50.4.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.1.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Tracker.Application\Tracker.Application.csproj" />
	</ItemGroup>
</Project>
