<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<GenerateMvcApplicationPartsAssemblyAttributes>false</GenerateMvcApplicationPartsAssemblyAttributes>
		<ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>
		<DebugType>portable</DebugType>
		<DebugSymbols>true</DebugSymbols>
		<HotReloadAutoRestart>true</HotReloadAutoRestart>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="Heron.MudCalendar" Version="3.4.0" />
		<PackageReference Include="Markdig" Version="0.45.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.6" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.6" PrivateAssets="all" />
		<PackageReference Include="MudBlazor" Version="8.15.0" />
		<PackageReference Include="Soenneker.Blazor.Drawflow" Version="4.0.346" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Tracker.Domain\Tracker.Domain.csproj" />
		<ProjectReference Include="..\Tracker.Services.Abstraction\Tracker.Services.Abstraction.csproj" />
		<ProjectReference Include="..\Tracker.Services\Tracker.Services.csproj" />
	</ItemGroup>

	<ItemGroup>
		<ServiceWorker Include="wwwroot\service-worker.js" PublishedContent="wwwroot\service-worker.published.js" />
	</ItemGroup>

</Project>
