<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="Scripts\001-Create-User.sql" />
		<EmbeddedResource Include="Scripts\002-Add-Refresh-Tokens.sql" />
		<EmbeddedResource Include="Scripts\003-Add-Role-Column.sql" />
		<EmbeddedResource Include="Scripts\004-Add-Role-Constrains.sql" />
		<EmbeddedResource Include="Scripts\005-Create-Workspaces-And-Boards.sql" />
		<EmbeddedResource Include="Scripts\006-Add-RoleEnum-To-User.sql" />
		<EmbeddedResource Include="Scripts\007-Change-Role-From-String-To-Enum.sql" />
		<EmbeddedResource Include="Scripts\008-Add-UserBoard-Relation.sql" />
		<EmbeddedResource Include="Scripts\009-Add-UserWorkspace-Relation.sql" />
		<EmbeddedResource Include="Scripts\010-Add-Board-Settings.sql" />
		<EmbeddedResource Include="Scripts\011-Add-Workspace-Settings.sql" />
		<EmbeddedResource Include="Scripts\012-Add-Workspace-Title-Index.sql" />
		<EmbeddedResource Include="Scripts\013-Add-Status-To-Task.sql" />
		<EmbeddedResource Include="Scripts\014-Make-Status-Not-Null-Set-Default.sql" />
		<EmbeddedResource Include="Scripts\015-Add-BoardItemAssignee.sql" />
		<EmbeddedResource Include="Scripts\016-Add-Item-Due-Date.sql" />
		<EmbeddedResource Include="Scripts\017-Add-Item-Importance.sql" />
		<EmbeddedResource Include="Scripts\018-Item-Importance-Not-Null.sql" />
		<EmbeddedResource Include="Scripts\019-Descriptions-Not-Null.sql" />
		<EmbeddedResource Include="Scripts\020-Rename-UserBoards-To-BoardUsers.sql" />
		<EmbeddedResource Include="Scripts\021-Rename-UserWorkspaces-To-WorkspaceUsers.sql" />
		<EmbeddedResource Include="Scripts\022-Add-Avatar-Version.sql" />
		<EmbeddedResource Include="Scripts\023-Add-BoardItemAttachment.sql" />
		<EmbeddedResource Include="Scripts\024-Add-ItemComments.sql" />
		<EmbeddedResource Include="Scripts\025-Add-CommentAttachments.sql" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="dbup" Version="5.0.41" />
		<PackageReference Include="dbup-sqlserver" Version="6.0.16" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Tracker.Domain\Tracker.Domain.csproj" />
	</ItemGroup>

</Project>
