CREATE TABLE [dbo].[Users] (
    [Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    [Email] NVARCHAR(50) NOT NULL UNIQUE,
    [PasswordHash] NVARCHAR(512) NOT NULL,
    [Username] NVARCHAR(30) NOT NULL UNIQUE,
    [FirstName] NVARCHAR(30) NOT NULL,
    [LastName] NVARCHAR(30) NOT NULL
);