ALTER TABLE [dbo].[Users]
ALTER COLUMN Email NVARCHAR(50) NOT NULL;

ALTER TABLE [dbo].[Users]
ALTER COLUMN Username NVARCHAR(30) NOT NULL;

ALTER TABLE [dbo].[Users]
ALTER COLUMN FirstName NVARCHAR(30) NOT NULL;

ALTER TABLE [dbo].[Users]
ALTER COLUMN LastName NVARCHAR(30) NULL;


ALTER TABLE [dbo].[Users]
ADD CONSTRAINT UX_Users_Username UNIQUE (Username);
